### ISSUE TITLE
Random Bot Fail/Self Termination (UPDTATE: Game issue, but leaving for Divoky to see)

### ISSUE THREAD

**Issue by grumpybobs** [div0ky/fsb_idle#23]
![Capture](https://user-images.githubusercontent.com/60832680/75033874-82293e00-5471-11ea-9d66-384ec5951930.PNG)

**Comment by grumpybobs** [comment]
![image0](https://user-images.githubusercontent.com/60832680/75034046-ee0ba680-5471-11ea-8b0f-8452d0826672.jpg)

**Comment by grumpybobs** [comment]
Continuing to self terminate.
restarted game. Did not work

Now it is stating I am not in guild, and I can not find any guild...so must be game issue, NOT bot issue

**Comment by div0ky** [comment]
This error was fixed in `v3.0.0-stable`. Thank you for your submission!
